### ISSUE TITLE
"You cannot trigger this objective yet"

### ISSUE THREAD

**Issue by MANIA420** [Tiefflieger06/mc-skyblock#1]
when using the /trigger skyblock command in a new world, all i get is "You cannot trigger this objective yet".

**Comment by Tiefflieger06** [comment]
This issue is likely caused by some mods that you have installed, as the "tick" functions are not being executed at all, even though this function is supposed to run every ingame tick. Try disabling and re-enabling mods until you find the one that causes the issue. This most likely isn't an issue caused by the datapack
